# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Render Deploy Action
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        # ID of the service to deploy
        service-id: ${{ secrets.SERVER_KEY }}
        # A Render API key
        api-key: ${{ secrets.USER_KEY }}
          
    - name: Deploy no EC2
      run: |
            echo "${{ secrets.KEY_EC2 }}" > chave_de_acesso && chmod 400 chave_de_acesso
            ssh -o StrictHostKeyChecking=no -i "chave_de_acesso" ubuntu@ec2-98-82-143-30.compute-1.amazonaws.com "
                  cd /home/ubuntu/springEasy-Render &&
                  git pull origin main &&
                  mvn clean package -DskipTests && 
                  ./executar.sh "
